### ISSUE TITLE
不明白开这个仓库有什么积极意义

### ISSUE THREAD

**Issue by WangNorthSea** [hoverwinter/HIT-OSLab#6]
“哈工大的操作系统课是本校CS课程中含金量最高的”，所以你上完课转头就把一份答案传上网了？这个仓库这么多star、fork，是因为你OS写得好吗？别闹了

**Comment by 24mlight** [comment]
> “哈工大的操作系统课是本校CS课程中含金量最高的”，所以你上完课转头就把一份答案传上网了？这个仓库这么多star、fork，是因为你OS写得好吗？别闹了

我个人觉得这位学长分享他的代码没什么不好的

**Comment by shutupandthinkhard** [comment]
> “哈工大的操作系统课是本校CS课程中含金量最高的”，所以你上完课转头就把一份答案传上网了？这个仓库这么多star、fork，是因为你OS写得好吗？别闹了

那详细展开说说您的想法呗?

**Comment by zhiyu-he** [comment]
> “哈工大的操作系统课是本校CS课程中含金量最高的”，所以你上完课转头就把一份答案传上网了？这个仓库这么多star、fork，是因为你OS写得好吗？别闹了


你核心想表达的是？

**Comment by rorschachandbat** [comment]
你酸了？

**Comment by echoechoin** [comment]
我觉得写的挺好的，我不是哈工大的，上网易云课堂，卡在一些地方查查你所谓的”答案“并没有什么不妥~

**Comment by MaXiaoYang6** [comment]
我觉得这个学长超级好啊，我是合工大学生，遇到不会的问题就来这里看看，您告诉我哪里不好了？？

**Comment by SEUsyx** [comment]
您多少有点疾病

**Comment by WangNorthSea** [comment]
> 您多少有点疾病

满嘴喷粪的废物，滚远点

**Comment by SEUsyx** [comment]
> > 您多少有点疾病
> 
> 满嘴喷粪的废物，滚远点

笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西

**Comment by WangNorthSea** [comment]
> > > 您多少有点疾病
> > 
> > 
> > 满嘴喷粪的废物，滚远点
> 
> 笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西

哎呀，炸出来一条蛆，抄答案的废物倒先开始说别人不学无术了真滑稽呢

**Comment by SEUsyx** [comment]
> > > > 您多少有点疾病
> > > 
> > > 
> > > 满嘴喷粪的废物，滚远点
> > 
> > 
> > 笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西
> 
> 哎呀，炸出来一条蛆，抄答案的废物倒先开始说别人不学无术了真滑稽呢

我又不用交作业，抄什么答案？看不惯你那嘴脸，现实中一定很失败吧，在网络上喷这喷那的，还有你骂人咋这么喜欢带屎，想家了？？还是想吃了？？

**Comment by WangNorthSea** [comment]
> > > > > 您多少有点疾病
> > > > 
> > > > 
> > > > 满嘴喷粪的废物，滚远点
> > > 
> > > 
> > > 笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西
> > 
> > 
> > 哎呀，炸出来一条蛆，抄答案的废物倒先开始说别人不学无术了真滑稽呢
> 
> 我又不用交作业，抄什么答案？看不惯你那嘴脸，现实中一定很失败吧，在网络上喷这喷那的，还有你骂人咋这么喜欢带屎，想家了？？还是想吃了？？
笑了，我一句话就炸出你这条蛆，说我失败，你跟我失败的人较劲你不是更失败？只怕是被人戳了肺管子，搁这无能狂怒呢

**Comment by SEUsyx** [comment]
> > > > > > 您多少有点疾病
> > > > > 
> > > > > 
> > > > > 满嘴喷粪的废物，滚远点
> > > > 
> > > > 
> > > > 笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西
> > > 
> > > 
> > > 哎呀，炸出来一条蛆，抄答案的废物倒先开始说别人不学无术了真滑稽呢
> > 
> > 
> > 我又不用交作业，抄什么答案？看不惯你那嘴脸，现实中一定很失败吧，在网络上喷这喷那的，还有你骂人咋这么喜欢带屎，想家了？？还是想吃了？？
> > 笑了，我一句话就炸出你这条蛆，说我失败，你跟我失败的人较劲你不是更失败？只怕是被人戳了肺管子，搁这无能狂怒呢

别笑了，你说的每句话都像是在骂自己，就这还能笑出来？多少脑子也不好使，自己看看自己说的啥，来我帮你回忆回忆：“是因为你OS写得好吗？别闹了”，九年义务教育就教出你这个智障？说话带刺还不觉得自己错了，礼貌呢？落在厕所了？

**Comment by WangNorthSea** [comment]
> > > > > > > 您多少有点疾病
> > > > > > 
> > > > > > 
> > > > > > 满嘴喷粪的废物，滚远点
> > > > > 
> > > > > 
> > > > > 笑了，碰上你这坨屎，谁都得躲远点，不学无术还只会酸别人的东西
> > > > 
> > > > 
> > > > 哎呀，炸出来一条蛆，抄答案的废物倒先开始说别人不学无术了真滑稽呢
> > > 
> > > 
> > > 我又不用交作业，抄什么答案？看不惯你那嘴脸，现实中一定很失败吧，在网络上喷这喷那的，还有你骂人咋这么喜欢带屎，想家了？？还是想吃了？？
> > > 笑了，我一句话就炸出你这条蛆，说我失败，你跟我失败的人较劲你不是更失败？只怕是被人戳了肺管子，搁这无能狂怒呢
> 
> 别笑了，你说的每句话都像是在骂自己，就这还能笑出来？多少脑子也不好使，自己看看自己说的啥，来我帮你回忆回忆：“是因为你OS写得好吗？别闹了”，九年义务教育就教出你这个智障？说话带刺还不觉得自己错了，礼貌呢？落在厕所了？

我就看你这傻卵会因为跟一个“失败人士”生气浪费多少时间，哈哈哈，废物
